[2024-07-22T17:05:56.043+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:05:56.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.merge_data scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-22T17:05:56.086+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.merge_data scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-22T17:05:56.086+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-22T17:05:56.103+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): merge_data> on 2024-07-18 00:00:00+00:00
[2024-07-22T17:05:56.114+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=57) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:05:56.116+0000] {standard_task_runner.py:63} INFO - Started process 59 to run task
[2024-07-22T17:05:56.116+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'merge_data', 'scheduled__2024-07-18T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpbt8226y9']
[2024-07-22T17:05:56.118+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask merge_data
[2024-07-22T17:05:56.181+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.merge_data scheduled__2024-07-18T00:00:00+00:00 [running]> on host ada6cb1e64b1
[2024-07-22T17:05:56.306+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-18T00:00:00+00:00'
[2024-07-22T17:05:56.308+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:06:04.614+0000] {demo.py:60} INFO - Data Merged
[2024-07-22T17:06:04.785+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:06:04.786+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:06:04.798+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=merge_data, run_id=scheduled__2024-07-18T00:00:00+00:00, execution_date=20240718T000000, start_date=20240722T170556, end_date=20240722T170604
[2024-07-22T17:06:04.828+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-22T17:06:04.854+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-22T17:06:04.856+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
