[2024-07-14T10:17:57.140+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: hello_airflow.task_hello scheduled__2024-06-09T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
